name: Copy ./tmp.txt on Main Branch

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    # env:
    #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: test start
        run: |
          echo "start"

    # steps:
    #   - name: Checkout repository
    #     uses: actions/checkout@v2

    #   - name: Check for changes in ./tmp.txt
    #     id: file_changes
    #     run: |
    #       if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) ]]; then
    #         echo "::set-output name=changed::true"
    #       fi
    #     shell: bash

    #   - name: Copy ./tmp.txt
    #     if: steps.file_changes.outputs.changed == 'true'
    #     run: |
    #       cp ./tmp.txt /path/to/destination/repo/tmp.txt
    #     shell: bash

    #   - name: Commit and push changes
    #     if: steps.file_changes.outputs.changed == 'true'
    #     run: |
    #       git config --global user.email "actions@github.com"
    #       git config --global user.name "GitHub Actions"
    #       git checkout -b tmp-action-1
    #       git add .
    #       git commit -m "Copy ./tmp.txt to another repository"
    #       git push
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
