name: Copy ./tmp.txt on Main Branch

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: test start
        run: |
          echo "start"

      # - name: Check for changes in ./tmp.txt
      #   id: file_changes
      #   run: |
      #     if [[ -n $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) ]]; then
      #       echo "::set-output name=changed::true"
      #     fi
      #   shell: bash
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      - name: clone another repository
        id: clone_from_another
        uses: actions/checkout@v3
        with:
          repository: tamtimtom08/pr_createe
          token: ${{ secrets.GH_PAT }} 
          path: ./target
      - name: testing
        run: |
          ls


      - name: Commit and push changes
        # if: steps.file_changes.outputs.changed == 'true'
        run: |
          cp ./main/tmp.txt ./target/tmp.txt
          cd target
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git branch
          git checkout -b tmp-action-1
          git add .
          git commit -m "Copy ./tmp.txt to another repository"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
