name: Copy ./tmp.txt on Main Branch

on:
  push:
    branches:
      - main

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup commit description
        env:
          RUN_URL: "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}"
          HEAD_COMMIT_URL: "${{ github.event.repository.html_url }}/commit/${{ github.event.after || github.sha }}"
        id: setup_description
        run: |
          DESCRIPTION=$(cat << EOF
          update Schema file 🚀

          created from ${{ env.RUN_URL }}
          latest commit: ${{ env.HEAD_COMMIT_URL }}
          EOF)
          DESCRIPTION="${DESCRIPTION//$'\n'/'%0A'}"
          echo "{name}={content}" >> $GITHUB_OUTPUT

      - name: Copy files
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'main.cpp'
          destination_repo: 'tamtimtom08/pr_createe'
          destination_folder: "api-schema"
          destination_branch: "main"
          destination_branch_create: "feature/update-graphql-schema_2"
          # user_email: "github-actions[bot]@users.noreply.github.com"
          user_email: "miwa.shiro.kuro@gmail.com"
          # user_name: "github-actions[bot]"
          user_name: "tamtimtom08"
          commit_message: ${{ steps.setup_description.outputs.content }}
          use_rsync: "true"
      - name: create Pull Request to another-repo
        run: |
          gh pr create \
            --title "update GraphQL Schema file " \
            --body "${{ steps.setup_description.outputs.content }}" \
            --repo micin-jp/chicken-web \
            --base main \
            --head feature/update-graphql-schema \
            --reviewer "${{ github.event.head_commit.committer.username || github.triggering_actor }}"
        env:
          GH_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}